# settings.yaml
selenium:
  drivers:
    chrome:
      path: "/path/to/chromedriver"  # Path to ChromeDriver executable
    firefox:
      path: "/path/to/geckodriver"   # Path to GeckoDriver executable
  browser: "firefox"                  # Browser to use (chrome/firefox)
  implicit_wait: 10                   # Implicit wait time in seconds
  headless: false                     # Run browser in headless mode

web:
  base_url: "https://www.example.com" # Base URL of the website
  login:
    url: "/login"                     # Login URL path
    credentials:
      username: "your_username"       # Username for login
      password: "your_password"       # Password for login

# Add more settings as needed
